---
- name: Install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

- name: Install Fisher
  shell: curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

- name: Install Fish-nvm
  shell: fisher install fisher install jorgebucaran/nvm.fish

- name: Install lastest Node
  shell: nvm install latest

- name: Get latest node version
  shell: node -v
  register: node_version

- name: Set LTS Node as default for new shells
  shell: set --universal nvm_default_version "{{ node_version.stdout }}"
