---
- name: Add gpg keys for the custom repos
  rpm_key:
    state: present
    key: ”{{ item }}"
  loop:
    - https://download.spotify.com/debian/pubkey_0D811D58.gpg
    - https://www.mongodb.org/static/pgp/server-4.4.asc
    - https://download.docker.com/linux/ubuntu/gpg
    - https://packages.microsoft.com/keys/microsoft.asc

- name: Add custom repositorys to apt
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - deb https://download.docker.com/linux/ubuntu focal stable
    - deb http://repository.spotify.com stable non-free
    - ppa:atareao/telegram
    - deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
    - deb [ arch=amd64,arm64,armhf ] https://packages.microsoft.com/repos/code stable main

- name: Update apt cache and install packages
  apt:
    state: latest
    update_cache: yes
    pkg:
      - spotify-client
      - telegram
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - whatsapp-desktop
      - code
      - mongodb-org

- name: Install .deb packages (Discord)
  apt:
    deb: https://discord.com/api/download?platform=linux&format=deb

- name: Fix time for dual boots
  shell: timedatectl set-local-rtc 1 --adjust-system-clock

- name: Get current login name
  shell: whoami
  register: host_username

- name: Create folder for git repos
  shell: mkdir /home/{{ host_username.stdout }}/Repos