---
- name: Add GPG key for MongoDB
  apt_key:
    state: present
    url: https://www.mongodb.org/static/pgp/server-4.4.asc

- name: Add GPG key for Docker
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker repo to apt
  apt_repository:
    repo: deb [ arch=amd64,trusted=yes ] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: true

- name: Add MongoDB repo to apt
  apt_repository:
    repo: deb [ trusted=yes ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
    state: present
    update_cache: true

- name: Remove no snap preferency
  file: 
    path: /etc/apt/preferences.d/nosnap.pref
    state: absent

- name: Update apt cache and install packages
  apt:
    state: latest
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - whatsapp-desktop
      - mongodb-org
      - snapd

- name: Install .deb packages (Discord)
  apt:
    deb: https://discord.com/api/download?platform=linux&format=deb

- name: Install snaps
  snap:
    name:
      - robo3t-snap
      - spotify
      - telegram-desktop

- name: Install classic snaps (VSCode)
  snap:
    classic: true
    name:
      - code

- name: Fix time for dual boots
  shell: timedatectl set-local-rtc 1 --adjust-system-clock
